/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Interfaces.Controles.*;
import Interfaces.Riesgos.*;

/**
 *
 * @author josue
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgHacker = new javax.swing.JLabel();
        btnAgregarActivo = new javax.swing.JButton();
        btnEditarActivo = new javax.swing.JButton();
        btnListarActivo = new javax.swing.JButton();
        imgIconMas = new javax.swing.JLabel();
        imgIconEditar = new javax.swing.JLabel();
        imgIconListar = new javax.swing.JLabel();
        btnAgregarRiesgo = new javax.swing.JButton();
        btnEditarRiesgo = new javax.swing.JButton();
        btnListarRiesgos = new javax.swing.JButton();
        btnAgregarControl = new javax.swing.JButton();
        btnEditarControl = new javax.swing.JButton();
        btnListarControles = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(756, 494));
        setSize(new java.awt.Dimension(756, 494));

        jPanel1.setBackground(new java.awt.Color(189, 221, 211));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 482));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 482));

        imgHacker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hacker50menos.png"))); // NOI18N

        btnAgregarActivo.setBackground(new java.awt.Color(94, 94, 94));
        btnAgregarActivo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAgregarActivo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarActivo.setText("Agregar Activo");
        btnAgregarActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActivoActionPerformed(evt);
            }
        });

        btnEditarActivo.setBackground(new java.awt.Color(94, 94, 94));
        btnEditarActivo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditarActivo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarActivo.setText("Editar Activo");
        btnEditarActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActivoActionPerformed(evt);
            }
        });

        btnListarActivo.setBackground(new java.awt.Color(94, 94, 94));
        btnListarActivo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnListarActivo.setForeground(new java.awt.Color(255, 255, 255));
        btnListarActivo.setText("Listar Activos");
        btnListarActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActivoActionPerformed(evt);
            }
        });

        imgIconMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N

        imgIconEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.png"))); // NOI18N

        imgIconListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/listar.png"))); // NOI18N

        btnAgregarRiesgo.setBackground(new java.awt.Color(94, 94, 94));
        btnAgregarRiesgo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAgregarRiesgo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarRiesgo.setText("Agregar Riesgo");
        btnAgregarRiesgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRiesgoActionPerformed(evt);
            }
        });

        btnEditarRiesgo.setBackground(new java.awt.Color(94, 94, 94));
        btnEditarRiesgo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditarRiesgo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarRiesgo.setText("Editar Riesgo");
        btnEditarRiesgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRiesgoActionPerformed(evt);
            }
        });

        btnListarRiesgos.setBackground(new java.awt.Color(94, 94, 94));
        btnListarRiesgos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnListarRiesgos.setForeground(new java.awt.Color(255, 255, 255));
        btnListarRiesgos.setText("Listar Riesgos");
        btnListarRiesgos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarRiesgosActionPerformed(evt);
            }
        });

        btnAgregarControl.setBackground(new java.awt.Color(94, 94, 94));
        btnAgregarControl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAgregarControl.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarControl.setText("Agregar Control");
        btnAgregarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarControlActionPerformed(evt);
            }
        });

        btnEditarControl.setBackground(new java.awt.Color(94, 94, 94));
        btnEditarControl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditarControl.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarControl.setText("Editar Control");
        btnEditarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarControlActionPerformed(evt);
            }
        });

        btnListarControles.setBackground(new java.awt.Color(94, 94, 94));
        btnListarControles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnListarControles.setForeground(new java.awt.Color(255, 255, 255));
        btnListarControles.setText("Listar Controles");
        btnListarControles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarControlesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setText("Aplicativo De Gestión De Activos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgIconEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgIconMas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgIconListar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListarActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(imgHacker)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListarRiesgos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnAgregarControl)
                        .addGap(27, 27, 27)
                        .addComponent(btnEditarControl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnListarControles))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarActivo)
                            .addComponent(imgIconMas))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgIconEditar)
                            .addComponent(btnEditarActivo))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgIconListar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnListarActivo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(imgHacker, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnAgregarRiesgo)
                        .addGap(54, 54, 54)
                        .addComponent(btnEditarRiesgo)
                        .addGap(50, 50, 50)
                        .addComponent(btnListarRiesgos)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarControl)
                    .addComponent(btnEditarControl)
                    .addComponent(btnListarControles))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActivoActionPerformed
        Agregar agregar = new Agregar();
        
        agregar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActivoActionPerformed

    private void btnListarActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActivoActionPerformed
        Listar listar = new Listar();
        
        listar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarActivoActionPerformed

    private void btnEditarActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActivoActionPerformed
        Editar editar = new Editar();
        
        editar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditarActivoActionPerformed

    private void btnAgregarRiesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRiesgoActionPerformed
        AgregarRiesgo agregarRiesgo = new AgregarRiesgo();
        
        agregarRiesgo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarRiesgoActionPerformed

    private void btnEditarRiesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRiesgoActionPerformed
        EditarRiesgo editarRiesgo = new EditarRiesgo();
        
        editarRiesgo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditarRiesgoActionPerformed

    private void btnListarRiesgosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarRiesgosActionPerformed
        ListarRiesgos enlistarRiesgos = new ListarRiesgos();
        
        enlistarRiesgos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarRiesgosActionPerformed

    private void btnAgregarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarControlActionPerformed
        AgregarControl agregarControl = new AgregarControl();
        
        agregarControl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarControlActionPerformed

    private void btnEditarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarControlActionPerformed
        EditarControl editarControles = new EditarControl();
        
        editarControles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditarControlActionPerformed

    private void btnListarControlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarControlesActionPerformed
        ListarControles listarControles = new ListarControles();
        
        listarControles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarControlesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarActivo;
    private javax.swing.JButton btnAgregarControl;
    private javax.swing.JButton btnAgregarRiesgo;
    private javax.swing.JButton btnEditarActivo;
    private javax.swing.JButton btnEditarControl;
    private javax.swing.JButton btnEditarRiesgo;
    private javax.swing.JButton btnListarActivo;
    private javax.swing.JButton btnListarControles;
    private javax.swing.JButton btnListarRiesgos;
    private javax.swing.JLabel imgHacker;
    private javax.swing.JLabel imgIconEditar;
    private javax.swing.JLabel imgIconListar;
    private javax.swing.JLabel imgIconMas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
